pipeline {
    agent { label 'builder' }
     options {
    lock("builder")
   }
    stages {
        stage('Build') {
            steps {
                sh 'echo "Hello world!"'
            }
        }
    }
}
